Checking for files to update...
Files found. Executing script...
Created Success Directory
Created Error Directory
Running Upsert Patient
Data Loader requires Java JRE 17 or later. Checking if it is installed...
2024-04-03 12:30:24,847 INFO  [main] process.ProcessRunner getInstance (ProcessRunner.java:310) - Initializing process engine
2024-04-03 12:30:24,847 INFO  [main] process.ProcessRunner getInstance (ProcessRunner.java:325) - process.nameis specified in the command line. Loading DynaBean with id upsertPatient from process-conf.xml located in folder C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf
2024-04-03 12:30:24,855 INFO  [main] process.ProcessConfig getBeanFactory (ProcessConfig.java:106) - Loading process configuration from config file: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\process-conf.xml
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2024-04-03 12:30:26,387 INFO  [upsertPatient] config.Config createDir (Config.java:1496) - Config folder already exists: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf
2024-04-03 12:30:26,387 INFO  [upsertPatient] config.Config getInstance (Config.java:1529) - Looking for file in config path: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\config.properties
2024-04-03 12:30:26,387 INFO  [upsertPatient] config.Config getInstance (Config.java:1560) - User config is found in C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\config.properties
2024-04-03 12:30:26,395 INFO  [upsertPatient] config.LastRun load (LastRun.java:87) - Last run info will be saved in file: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\upsert_lastRun.properties
2024-04-03 12:30:26,395 INFO  [upsertPatient] config.Config getInstance (Config.java:1567) - The controller config has been initialized
2024-04-03 12:30:26,403 INFO  [upsertPatient] process.ProcessRunner run (ProcessRunner.java:136) - Initializing process engine
2024-04-03 12:30:26,411 INFO  [upsertPatient] process.ProcessRunner run (ProcessRunner.java:156) - Logging in to: https://test.salesforce.com
2024-04-03 12:30:26,419 INFO  [upsertPatient] client.PartnerClient dologin (PartnerClient.java:626) - Beginning Partner Salesforce login ....
2024-04-03 12:30:26,436 INFO  [upsertPatient] client.PartnerClient loginInternal (PartnerClient.java:677) - Salesforce login to https://test.salesforce.com/services/Soap/u/60.0/ as user supersaml@wisewolves.com.wisewolves
2024-04-03 12:30:27,185 ERROR [upsertPatient] client.PartnerClient runOperation (PartnerClient.java:379) - Error while calling web service operation: login, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:27,193 ERROR [upsertPatient] client.PartnerClient runOperation (PartnerClient.java:385) - Error while calling web service operation: login, error was: Invalid username, password, security token; or user locked out.
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:27,200 ERROR [upsertPatient] client.PartnerClient loginInternal (PartnerClient.java:693) - Error while logging in to web service at: https://test.salesforce.com/services/Soap/u/60.0/, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:27,200 WARN  [upsertPatient] client.PartnerClient login (PartnerClient.java:605) - Failed to authenticate using URL https://test.salesforce.com specified in the property sfdc.endpoint. Error: 
2024-04-03 12:30:27,200 INFO  [upsertPatient] client.PartnerClient login (PartnerClient.java:614) - Retrying to authenticate using username/password server URL https://login.salesforce.com by setting the property sfdc.endpoint
2024-04-03 12:30:27,200 INFO  [upsertPatient] client.PartnerClient dologin (PartnerClient.java:626) - Beginning Partner Salesforce login ....
2024-04-03 12:30:27,200 INFO  [upsertPatient] client.PartnerClient loginInternal (PartnerClient.java:677) - Salesforce login to https://login.salesforce.com/services/Soap/u/60.0/ as user supersaml@wisewolves.com.wisewolves
2024-04-03 12:30:33,909 ERROR [upsertPatient] client.PartnerClient runOperation (PartnerClient.java:379) - Error while calling web service operation: login, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:33,909 ERROR [upsertPatient] client.PartnerClient runOperation (PartnerClient.java:385) - Error while calling web service operation: login, error was: Invalid username, password, security token; or user locked out.
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:33,909 ERROR [upsertPatient] client.PartnerClient loginInternal (PartnerClient.java:693) - Error while logging in to web service at: https://login.salesforce.com/services/Soap/u/60.0/, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:33,909 WARN  [upsertPatient] client.PartnerClient login (PartnerClient.java:605) - Failed to authenticate using URL https://login.salesforce.com specified in the property sfdc.endpoint. Error: 
2024-04-03 12:30:33,909 ERROR [upsertPatient] client.PartnerClient login (PartnerClient.java:617) - Failed to get user info using manually configured session id
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:33,909 FATAL [main] process.ProcessRunner logErrorAndExitProcess (ProcessRunner.java:253) - Unable to run process
java.lang.RuntimeException: Invalid username, password, security token; or user locked out.
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:183) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
Caused by: com.sforce.soap.partner.fault.LoginFault
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) ~[dataloader-60.0.2.jar:?]
	... 3 more
An error occurred during "Patient". Check DataLoader logs for details.
Running Upsert EncounterOrg
Data Loader requires Java JRE 17 or later. Checking if it is installed...
2024-04-03 12:30:37,739 INFO  [main] process.ProcessRunner getInstance (ProcessRunner.java:310) - Initializing process engine
2024-04-03 12:30:37,739 INFO  [main] process.ProcessRunner getInstance (ProcessRunner.java:325) - process.nameis specified in the command line. Loading DynaBean with id upsertEncounterOrg from process-conf.xml located in folder C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf
2024-04-03 12:30:37,747 INFO  [main] process.ProcessConfig getBeanFactory (ProcessConfig.java:106) - Loading process configuration from config file: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\process-conf.xml
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2024-04-03 12:30:39,036 INFO  [upsertEncounterOrg] config.Config createDir (Config.java:1496) - Config folder already exists: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf
2024-04-03 12:30:39,036 INFO  [upsertEncounterOrg] config.Config getInstance (Config.java:1529) - Looking for file in config path: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\config.properties
2024-04-03 12:30:39,036 INFO  [upsertEncounterOrg] config.Config getInstance (Config.java:1560) - User config is found in C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\config.properties
2024-04-03 12:30:39,036 INFO  [upsertEncounterOrg] config.LastRun load (LastRun.java:87) - Last run info will be saved in file: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\upsert_lastRun.properties
2024-04-03 12:30:39,044 INFO  [upsertEncounterOrg] config.Config getInstance (Config.java:1567) - The controller config has been initialized
2024-04-03 12:30:39,044 INFO  [upsertEncounterOrg] process.ProcessRunner run (ProcessRunner.java:136) - Initializing process engine
2024-04-03 12:30:39,051 INFO  [upsertEncounterOrg] process.ProcessRunner run (ProcessRunner.java:156) - Logging in to: https://test.salesforce.com
2024-04-03 12:30:39,060 INFO  [upsertEncounterOrg] client.PartnerClient dologin (PartnerClient.java:626) - Beginning Partner Salesforce login ....
2024-04-03 12:30:39,084 INFO  [upsertEncounterOrg] client.PartnerClient loginInternal (PartnerClient.java:677) - Salesforce login to https://test.salesforce.com/services/Soap/u/60.0/ as user supersaml@wisewolves.com.wisewolves
2024-04-03 12:30:39,813 ERROR [upsertEncounterOrg] client.PartnerClient runOperation (PartnerClient.java:379) - Error while calling web service operation: login, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:39,822 ERROR [upsertEncounterOrg] client.PartnerClient runOperation (PartnerClient.java:385) - Error while calling web service operation: login, error was: Invalid username, password, security token; or user locked out.
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:39,822 ERROR [upsertEncounterOrg] client.PartnerClient loginInternal (PartnerClient.java:693) - Error while logging in to web service at: https://test.salesforce.com/services/Soap/u/60.0/, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:39,822 WARN  [upsertEncounterOrg] client.PartnerClient login (PartnerClient.java:605) - Failed to authenticate using URL https://test.salesforce.com specified in the property sfdc.endpoint. Error: 
2024-04-03 12:30:39,822 INFO  [upsertEncounterOrg] client.PartnerClient login (PartnerClient.java:614) - Retrying to authenticate using username/password server URL https://login.salesforce.com by setting the property sfdc.endpoint
2024-04-03 12:30:39,822 INFO  [upsertEncounterOrg] client.PartnerClient dologin (PartnerClient.java:626) - Beginning Partner Salesforce login ....
2024-04-03 12:30:39,822 INFO  [upsertEncounterOrg] client.PartnerClient loginInternal (PartnerClient.java:677) - Salesforce login to https://login.salesforce.com/services/Soap/u/60.0/ as user supersaml@wisewolves.com.wisewolves
2024-04-03 12:30:45,792 ERROR [upsertEncounterOrg] client.PartnerClient runOperation (PartnerClient.java:379) - Error while calling web service operation: login, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:45,792 ERROR [upsertEncounterOrg] client.PartnerClient runOperation (PartnerClient.java:385) - Error while calling web service operation: login, error was: Invalid username, password, security token; or user locked out.
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:45,792 ERROR [upsertEncounterOrg] client.PartnerClient loginInternal (PartnerClient.java:693) - Error while logging in to web service at: https://login.salesforce.com/services/Soap/u/60.0/, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:45,792 WARN  [upsertEncounterOrg] client.PartnerClient login (PartnerClient.java:605) - Failed to authenticate using URL https://login.salesforce.com specified in the property sfdc.endpoint. Error: 
2024-04-03 12:30:45,792 ERROR [upsertEncounterOrg] client.PartnerClient login (PartnerClient.java:617) - Failed to get user info using manually configured session id
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:45,792 FATAL [main] process.ProcessRunner logErrorAndExitProcess (ProcessRunner.java:253) - Unable to run process
java.lang.RuntimeException: Invalid username, password, security token; or user locked out.
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:183) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
Caused by: com.sforce.soap.partner.fault.LoginFault
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) ~[dataloader-60.0.2.jar:?]
	... 3 more
An error occurred during "EncounterOrg". Check DataLoader logs for details.
Running Upsert ProviderContact
Data Loader requires Java JRE 17 or later. Checking if it is installed...
2024-04-03 12:30:49,812 INFO  [main] process.ProcessRunner getInstance (ProcessRunner.java:310) - Initializing process engine
2024-04-03 12:30:49,812 INFO  [main] process.ProcessRunner getInstance (ProcessRunner.java:325) - process.nameis specified in the command line. Loading DynaBean with id upsertProviderContact from process-conf.xml located in folder C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf
2024-04-03 12:30:49,812 INFO  [main] process.ProcessConfig getBeanFactory (ProcessConfig.java:106) - Loading process configuration from config file: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\process-conf.xml
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2024-04-03 12:30:52,339 INFO  [upsertProviderContact] config.Config createDir (Config.java:1496) - Config folder already exists: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf
2024-04-03 12:30:52,339 INFO  [upsertProviderContact] config.Config getInstance (Config.java:1529) - Looking for file in config path: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\config.properties
2024-04-03 12:30:52,339 INFO  [upsertProviderContact] config.Config getInstance (Config.java:1560) - User config is found in C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\config.properties
2024-04-03 12:30:52,347 INFO  [upsertProviderContact] config.LastRun load (LastRun.java:87) - Last run info will be saved in file: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\upsert_lastRun.properties
2024-04-03 12:30:52,347 INFO  [upsertProviderContact] config.Config getInstance (Config.java:1567) - The controller config has been initialized
2024-04-03 12:30:52,347 INFO  [upsertProviderContact] process.ProcessRunner run (ProcessRunner.java:136) - Initializing process engine
2024-04-03 12:30:52,363 INFO  [upsertProviderContact] process.ProcessRunner run (ProcessRunner.java:156) - Logging in to: https://test.salesforce.com
2024-04-03 12:30:52,363 INFO  [upsertProviderContact] client.PartnerClient dologin (PartnerClient.java:626) - Beginning Partner Salesforce login ....
2024-04-03 12:30:52,387 INFO  [upsertProviderContact] client.PartnerClient loginInternal (PartnerClient.java:677) - Salesforce login to https://test.salesforce.com/services/Soap/u/60.0/ as user supersaml@wisewolves.com.wisewolves
2024-04-03 12:30:53,128 ERROR [upsertProviderContact] client.PartnerClient runOperation (PartnerClient.java:379) - Error while calling web service operation: login, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:53,136 ERROR [upsertProviderContact] client.PartnerClient runOperation (PartnerClient.java:385) - Error while calling web service operation: login, error was: Invalid username, password, security token; or user locked out.
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:53,136 ERROR [upsertProviderContact] client.PartnerClient loginInternal (PartnerClient.java:693) - Error while logging in to web service at: https://test.salesforce.com/services/Soap/u/60.0/, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:53,136 WARN  [upsertProviderContact] client.PartnerClient login (PartnerClient.java:605) - Failed to authenticate using URL https://test.salesforce.com specified in the property sfdc.endpoint. Error: 
2024-04-03 12:30:53,136 INFO  [upsertProviderContact] client.PartnerClient login (PartnerClient.java:614) - Retrying to authenticate using username/password server URL https://login.salesforce.com by setting the property sfdc.endpoint
2024-04-03 12:30:53,136 INFO  [upsertProviderContact] client.PartnerClient dologin (PartnerClient.java:626) - Beginning Partner Salesforce login ....
2024-04-03 12:30:53,136 INFO  [upsertProviderContact] client.PartnerClient loginInternal (PartnerClient.java:677) - Salesforce login to https://login.salesforce.com/services/Soap/u/60.0/ as user supersaml@wisewolves.com.wisewolves
2024-04-03 12:30:59,512 ERROR [upsertProviderContact] client.PartnerClient runOperation (PartnerClient.java:379) - Error while calling web service operation: login, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:59,512 ERROR [upsertProviderContact] client.PartnerClient runOperation (PartnerClient.java:385) - Error while calling web service operation: login, error was: Invalid username, password, security token; or user locked out.
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:59,512 ERROR [upsertProviderContact] client.PartnerClient loginInternal (PartnerClient.java:693) - Error while logging in to web service at: https://login.salesforce.com/services/Soap/u/60.0/, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03T18:30:59.536990900Z upsertProviderContact ERROR Unable to delete file C:\Users\david\AppData\Local\Temp\sdl.log: java.nio.file.FileSystemException C:\Users\david\AppData\Local\Temp\sdl.log: The process cannot access the file because it is being used by another process
2024-04-03 12:30:59,512 WARN  [upsertProviderContact] client.PartnerClient login (PartnerClient.java:605) - Failed to authenticate using URL https://login.salesforce.com specified in the property sfdc.endpoint. Error: 
2024-04-03 12:30:59,536 ERROR [upsertProviderContact] client.PartnerClient login (PartnerClient.java:617) - Failed to get user info using manually configured session id
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:30:59,536 FATAL [main] process.ProcessRunner logErrorAndExitProcess (ProcessRunner.java:253) - Unable to run process
java.lang.RuntimeException: Invalid username, password, security token; or user locked out.
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:183) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
Caused by: com.sforce.soap.partner.fault.LoginFault
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) ~[dataloader-60.0.2.jar:?]
	... 3 more
An error occurred during "ProviderContact". Check DataLoader logs for details.
Running Upsert Clinical Encounter
Data Loader requires Java JRE 17 or later. Checking if it is installed...
2024-04-03 12:31:03,496 INFO  [main] process.ProcessRunner getInstance (ProcessRunner.java:310) - Initializing process engine
2024-04-03 12:31:03,496 INFO  [main] process.ProcessRunner getInstance (ProcessRunner.java:325) - process.nameis specified in the command line. Loading DynaBean with id upsertClinicalEncounter from process-conf.xml located in folder C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf
2024-04-03 12:31:03,496 INFO  [main] process.ProcessConfig getBeanFactory (ProcessConfig.java:106) - Loading process configuration from config file: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\process-conf.xml
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2024-04-03 12:31:04,876 INFO  [upsertClinicalEncounter] config.Config createDir (Config.java:1496) - Config folder already exists: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf
2024-04-03 12:31:04,877 INFO  [upsertClinicalEncounter] config.Config getInstance (Config.java:1529) - Looking for file in config path: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\config.properties
2024-04-03 12:31:04,877 INFO  [upsertClinicalEncounter] config.Config getInstance (Config.java:1560) - User config is found in C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\config.properties
2024-04-03 12:31:04,877 INFO  [upsertClinicalEncounter] config.LastRun load (LastRun.java:87) - Last run info will be saved in file: C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Conf\upsert_lastRun.properties
2024-04-03 12:31:04,884 INFO  [upsertClinicalEncounter] config.Config getInstance (Config.java:1567) - The controller config has been initialized
2024-04-03 12:31:04,884 INFO  [upsertClinicalEncounter] process.ProcessRunner run (ProcessRunner.java:136) - Initializing process engine
2024-04-03 12:31:04,892 INFO  [upsertClinicalEncounter] process.ProcessRunner run (ProcessRunner.java:156) - Logging in to: https://test.salesforce.com
2024-04-03 12:31:04,901 INFO  [upsertClinicalEncounter] client.PartnerClient dologin (PartnerClient.java:626) - Beginning Partner Salesforce login ....
2024-04-03 12:31:04,916 INFO  [upsertClinicalEncounter] client.PartnerClient loginInternal (PartnerClient.java:677) - Salesforce login to https://test.salesforce.com/services/Soap/u/60.0/ as user supersaml@wisewolves.com.wisewolves
2024-04-03 12:31:05,683 ERROR [upsertClinicalEncounter] client.PartnerClient runOperation (PartnerClient.java:379) - Error while calling web service operation: login, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:31:05,691 ERROR [upsertClinicalEncounter] client.PartnerClient runOperation (PartnerClient.java:385) - Error while calling web service operation: login, error was: Invalid username, password, security token; or user locked out.
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:31:05,691 ERROR [upsertClinicalEncounter] client.PartnerClient loginInternal (PartnerClient.java:693) - Error while logging in to web service at: https://test.salesforce.com/services/Soap/u/60.0/, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:31:05,691 WARN  [upsertClinicalEncounter] client.PartnerClient login (PartnerClient.java:605) - Failed to authenticate using URL https://test.salesforce.com specified in the property sfdc.endpoint. Error: 
2024-04-03 12:31:05,691 INFO  [upsertClinicalEncounter] client.PartnerClient login (PartnerClient.java:614) - Retrying to authenticate using username/password server URL https://login.salesforce.com by setting the property sfdc.endpoint
2024-04-03 12:31:05,691 INFO  [upsertClinicalEncounter] client.PartnerClient dologin (PartnerClient.java:626) - Beginning Partner Salesforce login ....
2024-04-03 12:31:05,691 INFO  [upsertClinicalEncounter] client.PartnerClient loginInternal (PartnerClient.java:677) - Salesforce login to https://login.salesforce.com/services/Soap/u/60.0/ as user supersaml@wisewolves.com.wisewolves
2024-04-03 12:31:13,232 ERROR [upsertClinicalEncounter] client.PartnerClient runOperation (PartnerClient.java:379) - Error while calling web service operation: login, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:31:13,232 ERROR [upsertClinicalEncounter] client.PartnerClient runOperation (PartnerClient.java:385) - Error while calling web service operation: login, error was: Invalid username, password, security token; or user locked out.
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:31:13,232 ERROR [upsertClinicalEncounter] client.PartnerClient loginInternal (PartnerClient.java:693) - Error while logging in to web service at: https://login.salesforce.com/services/Soap/u/60.0/, error was: 
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:31:13,232 WARN  [upsertClinicalEncounter] client.PartnerClient login (PartnerClient.java:605) - Failed to authenticate using URL https://login.salesforce.com specified in the property sfdc.endpoint. Error: 
2024-04-03 12:31:13,240 ERROR [upsertClinicalEncounter] client.PartnerClient login (PartnerClient.java:617) - Failed to get user info using manually configured session id
com.sforce.soap.partner.fault.LoginFault: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
2024-04-03 12:31:13,240 FATAL [main] process.ProcessRunner logErrorAndExitProcess (ProcessRunner.java:253) - Unable to run process
java.lang.RuntimeException: Invalid username, password, security token; or user locked out.
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:183) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:93) [dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72) [dataloader-60.0.2.jar:?]
Caused by: com.sforce.soap.partner.fault.LoginFault
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:721) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:593) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:250) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:224) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:163) ~[dataloader-60.0.2.jar:?]
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108) ~[dataloader-60.0.2.jar:?]
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:817) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:198) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient$9.run(PartnerClient.java:189) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:373) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:678) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.dologin(PartnerClient.java:642) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:592) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:615) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:250) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:216) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:211) ~[dataloader-60.0.2.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:157) ~[dataloader-60.0.2.jar:?]
	... 3 more
An error occurred during "ClinicalEncounter". Check DataLoader logs for details.
All processes completed successfully.
Moving files to the Updated folder...
C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Data\ToUpdate\ClinicalEncounters.csv
C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Data\ToUpdate\EncounterOrgs.csv
C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Data\ToUpdate\Patients.csv
C:\Users\david\OneDrive\Documentos\WiseWolves\Bamboo\dataloader_v60.0.2\Bamboo\Data\ToUpdate\ProviderContacts.csv
        4 file(s) moved.
